library(lubridate)
library(lattice)
library(sqldf)
houseFile <- read.csv.sql("household_power_consumption.txt", sql = 'select * from file where Date ="1/2/2007" or Date = "2/2/2007"', sep= ";")
houseFile$date_time <- dmy_hms(paste(houseFile$Date,houseFile$Time ))
houseFile$Global_active_power <- as.numeric(houseFile$Global_active_power)
par(bg = NA)
plot(houseFile$date_time,houseFile$Global_active_power,type = "l", xlab = "",ylab = "Global active power (kilowatts)")
dev.copy(png, file ="plot2.png",width = 480, height = 480)
dev.off()